from dataclasses import dataclass
from datetime import datetime

PLANETS = ("mercury", "venus", "mars", "jupiter", "saturn",
           "uranus", "neptune")
KNOWN_BODIES = set(PLANETS) | {"moon", "sun"}

# canonical body order for uids / matching keys: sun, moon, planets outward
BODY_RANK = {name: i for i, name in enumerate(("sun", "moon") + PLANETS)}


def canonical(bodies) -> tuple:
    return tuple(sorted(bodies, key=BODY_RANK.__getitem__))


@dataclass
class Rec:
    """One event, either generated by us or parsed from the feed.

    type matches skyevents EventType values, plus "ra_conjunction" for
    the feed's RA-equality conjunctions (we do not generate those, but
    compare against them to measure the definitional time offset).
    kind disambiguates within a type: phase / season name, apsis side,
    conjunction flavour, elongation side, eclipse kind, shower name.
    """

    type: str
    bodies: tuple
    dt: datetime
    kind: str = ""
    summary: str = ""
    extra: dict = None

    @property
    def key(self):
        return (self.type, self.bodies, self.kind)

    def __str__(self):
        bodies = "-".join(self.bodies)
        when = self.dt.strftime("%Y-%m-%d %H:%M")
        return f"{when}  {self.type}({self.kind}) {bodies}"
